version: '3.9'
services:
  admin-backend:
    build: 
      context: ../
      dockerfile: ./.ci-cd/Dockerfile
    image: greenbonetask:first
    env_file:
      - .env_file
    ports:
      - "80:80"
      - "443:443"
  admin-notification:
    image: greenbone/exercise-admin-notification